dist: trusty
sudo: required
language: generic
notifications:
  email:
    on_success: change
    on_failure: change
jobs:
  include:
  - stage: build
    name: Build latest tag
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build . -t commontheory/alpine-eos:latest
    - docker push commontheory/alpine-eos:latest
stages:
- build
