version: 2
jobs:
  - build_push:
    machine:
      enabled: true
    steps:
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build . -t commontheory/alpine-eos:latest
        docker push -t commontheory/alpine-eos:latest
workflows:
  version: 2
  build_push:
    jobs:
      - build
